### ISSUE TITLE
java.lang.IllegalStateException: Accessibility off

### ISSUE THREAD

**Issue by danimahardhika** [danimahardhika/cafebar#3]
```gradle
Fatal Exception: java.lang.IllegalStateException: Accessibility off. Did you forget to check that?
       at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:380)
       at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:6767)
       at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
       at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
       at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
       at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:891)
       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6306)
       at android.view.View.sendAccessibilityEventUnchecked(View.java:6285)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:7539)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:7565)
       at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:6677)
       at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:6861)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3138)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3138)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3138)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3138)
       at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:9441)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4517)
       at android.view.ViewGroup.addView(ViewGroup.java:4297)
       at android.view.ViewGroup.addView(ViewGroup.java:4237)
       at android.view.ViewGroup.addView(ViewGroup.java:4210)
       at android.support.design.widget.BaseTransientBottomBar.showView(SourceFile:436)
       at android.support.design.widget.BaseTransientBottomBar$1.handleMessage(SourceFile:177)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by danimahardhika** [comment]
Got another crash report from Pixel 2 XL
